---
email_notification: "email@yourdomain.xxx"
logsurfer_user: "logsurf"
install_prefix: "/usr/local"
logsurfer_path: "/var/logsurfer"
register_connector: true
ezyadmin_api_url: https://api.netway.ezyadmin.com
ezyadmin_connector: logsurfer
